version: '3'

services:
  node:
    build:
      context: ./docker
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd react-app && yarn start'
    ports:
      - '3333:3000'
    stdin_open: true